npmRegistryServer: "https://registry.npmmirror.com"
disturl: "http://npmmirror.com/mirrors/node"
nvm_nodejs_org_mirror: "http://npmmirror.com/mirrors/node"
NODEJS_ORG_MIRROR: "http://npmmirror.com/mirrors/node"
sass_binary_site: "http://npmmirror.com/mirrors/node-sass"
electron_mirror: "http://npmmirror.com/mirrors/electron/"
SQLITE3_BINARY_SITE: "http://npmmirror.com/mirrors/sqlite3"
profiler_binary_host_mirror: "http://npmmirror.com/mirrors/node-inspector/"
node_inspector_cdnurl: "https://npmmirror.com/mirrors/node-inspector"
selenium_cdnurl: "https://npmmirror.com/mirrors/selenium/"
puppeteer_download_host: "https://npmmirror.com/mirrors"
chromedriver_cdnurl: "https://npmmirror.com/mirrors/chromedriver/"
operadriver_cdnurl: "https://npmmirror.com/mirrors/operadriver"
phantomjs_cdnurl: "https://npmmirror.com/mirrors/phantomjs"
fse_binary_host_mirror: "https://npmmirror.com/mirrors/fsevents"
sharp_binary_host: "https://npmmirror.com/mirrors/sharp"
sharp_libvips_binary_host: "https://npmmirror.com/mirrors/sharp-libvips"